# Alternative conda environment file
# Use with: conda env create -f environment.yml

name: pill_project
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  
  # Core web framework
  - fastapi=0.104.1
  - uvicorn=0.24.0
  - starlette=0.27.0
  
  # Data processing
  - pandas=2.1.3
  - numpy
  
  # Database
  - sqlalchemy=1.4.39
  - psycopg2=2.9.9
  
  # HTTP clients
  - aiohttp=3.8.6
  - httpx=0.25.1
  - requests=2.31.0
  
  # Additional dependencies via pip
  - pip:
    - pydantic==2.4.2
    - python-multipart==0.0.6
    - aiofiles==23.2.1
    - typing_extensions==4.8.0
    - python-dotenv==1.0.0