"""Admin image upload/management endpoints."""
import asyncio
import io
import os
import re
import logging
import time
import unicodedata
import uuid
import zipfile
from typing import Optional

import httpx
from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile
from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError

import database
from routes.admin.auth import get_admin_user, log_audit

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/admin/pills", tags=["admin-images"])

ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}
MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB per individual image
MAX_ZIP_SIZE = int(os.getenv("MAX_ZIP_SIZE_MB", "50")) * 1024 * 1024  # default 50 MB (compressed)
MAX_IMAGES_PER_ZIP = int(os.getenv("MAX_IMAGES_PER_ZIP", "500"))
SUPABASE_URL = os.getenv("NEXT_PUBLIC_SUPABASE_URL", "")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "")
STORAGE_BUCKET = os.getenv("STORAGE_BUCKET", "images")
# Limit concurrent Supabase uploads per batch to avoid hammering the storage API
_ZIP_UPLOAD_CONCURRENCY = int(os.getenv("ZIP_UPLOAD_CONCURRENCY", "10"))

_CONTENT_TYPE_MAP = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
}


def _generate_slug(name: str) -> str:
    """
    Slugify a medicine_name string: lowercase, strip diacritics, collapse
    non-alphanumeric runs to '-'.

    This is a fallback for pills that have no stored slug column.  It only
    uses medicine_name (not spl_strength).  Pills whose slug was generated by
    the wizard's generateSlug() (which combines name + strength) will be
    matched via the slug column lookup *before* this fallback is reached.
    """
    if not name:
        return ""
    s = name.lower()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = s.strip("-")
    return s


def _strip_variant_suffix(stem: str) -> str:
    """Strip a trailing '-<number>' variant suffix, e.g. 'drug-1' → 'drug'."""
    return re.sub(r"-\d+$", "", stem)


def _normalize_ndc11(value: str) -> str:
    """Strip hyphens and return bare digits, e.g. '41163-0249-01' → '41163024901'."""
    return re.sub(r"-", "", value).strip()


def _supabase_upload(path: str, data: bytes, content_type: str) -> bool:
    """Upload a file to Supabase Storage synchronously. Returns True on success.

    Used by the single-image upload endpoint. Do NOT change this function's
    signature or behaviour to preserve existing endpoint compatibility.
    """
    if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
        logger.warning("Supabase credentials not configured — skipping storage upload")
        return False
    try:
        resp = httpx.post(
            f"{SUPABASE_URL}/storage/v1/object/{STORAGE_BUCKET}/{path}",
            headers={
                "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
                "Content-Type": content_type,
            },
            content=data,
            timeout=30,
        )
        if resp.status_code in (200, 201):
            return True
        logger.error(f"Supabase upload failed: {resp.status_code} — {resp.text[:200]}")
        return False
    except Exception as e:
        logger.error(f"Supabase upload error: {e}")
        return False


async def _async_supabase_upload(path: str, data: bytes, content_type: str) -> bool:
    """Upload a file to Supabase Storage asynchronously. Returns True on success.

    Used by the bulk ZIP endpoint via asyncio.gather to avoid blocking the
    event loop on large batches.
    """
    if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
        logger.warning("Supabase credentials not configured — skipping storage upload")
        return False
    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                f"{SUPABASE_URL}/storage/v1/object/{STORAGE_BUCKET}/{path}",
                headers={
                    "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
                    "Content-Type": content_type,
                },
                content=data,
                timeout=30,
            )
        if resp.status_code in (200, 201):
            return True
        logger.error(f"Supabase async upload failed: {resp.status_code} — {resp.text[:200]}")
        return False
    except Exception as e:
        logger.error(f"Supabase async upload error: {e}")
        return False


@router.post("/bulk-images/zip", status_code=200)
async def upload_images_zip(
    request: Request,
    file: UploadFile = File(...),
    admin: dict = Depends(get_admin_user),
):
    """
    Accept a ZIP file, extract images in-memory, match each to a pill by NDC11 /
    slug / medicine_name slug (with variant-suffix stripping), upload to Supabase
    Storage concurrently, and append storage paths to pillfinder.image_filename.

    Matching priority (per image stem, with hyphen-normalised NDC support):
      1. NDC11 (stem digits == 11, hyphens stripped before comparison)
      2. pillfinder.slug column (case-insensitive)
      3. Slugified medicine_name (fallback for pills without a slug column)
      4. Each of the above retried after stripping a trailing '-<N>' suffix

    Images are only matched against non-deleted pills, ordered by
    most-recently-updated first so the newest record wins on slug collisions.

    Returns structured JSON with counts and per-file results.
    Does NOT modify the existing single-image upload endpoint behaviour.
    """
    if admin["role"] not in ("superuser", "editor", "reviewer"):
        raise HTTPException(status_code=403, detail="Requires editor role or higher")

    fname = (file.filename or "").lower()
    if not fname.endswith(".zip"):
        raise HTTPException(status_code=400, detail="Only .zip files are accepted")

    content = await file.read()
    if len(content) > MAX_ZIP_SIZE:
        raise HTTPException(
            status_code=400,
            detail=f"ZIP file too large (max {MAX_ZIP_SIZE // 1024 // 1024} MB)",
        )

    if not zipfile.is_zipfile(io.BytesIO(content)):
        raise HTTPException(status_code=400, detail="File is not a valid ZIP archive")

    zf = zipfile.ZipFile(io.BytesIO(content))

    # Collect only valid image entries (skip directories, hidden files, __MACOSX artifacts)
    image_entries = [
        name
        for name in zf.namelist()
        if os.path.splitext(name.lower())[1] in ALLOWED_EXTENSIONS
        and os.path.basename(name)
        and not os.path.basename(name).startswith(".")
        and "__MACOSX" not in name
    ]

    if len(image_entries) > MAX_IMAGES_PER_ZIP:
        raise HTTPException(
            status_code=400,
            detail=f"ZIP contains too many images (max {MAX_IMAGES_PER_ZIP})",
        )

    # ── Load pill lookup tables ────────────────────────────────────────────
    # Ordered by most-recently-updated non-deleted rows first so that setdefault
    # below keeps the newest match when slugs/names collide.
    if not database.db_engine:
        database.connect_to_database()

    # All maps use setdefault so the first row encountered (newest) wins
    ndc11_map: dict = {}   # "12345678901" (bare digits) -> row tuple
    slug_map: dict = {}    # "aspirin-500-mg"            -> row tuple
    name_slug_map: dict = {}  # slugified medicine_name  -> row tuple

    try:
        with database.db_engine.connect() as conn:
            rows = conn.execute(
                text(
                    "SELECT id, medicine_name, slug, ndc11, image_filename"
                    " FROM pillfinder"
                    " WHERE deleted_at IS NULL"
                    " ORDER BY updated_at DESC NULLS LAST, id ASC"
                )
            ).fetchall()
    except SQLAlchemyError as e:
        logger.error(f"upload_images_zip DB load error: {e}")
        raise HTTPException(status_code=500, detail="Database error loading pill data")

    for row in rows:
        _pill_id_r, medicine_name, slug, ndc11, _image_filename = row
        if ndc11:
            normalized = _normalize_ndc11(str(ndc11))
            if normalized.isdigit() and len(normalized) == 11:
                ndc11_map.setdefault(normalized, row)
        if slug:
            slug_map.setdefault(slug.strip().lower(), row)
        if medicine_name:
            ns = _generate_slug(medicine_name)
            if ns:
                name_slug_map.setdefault(ns, row)

    # ── Helper: resolve a single stem to a row ────────────────────────────
    def _lookup(s: str) -> Optional[tuple]:
        # NDC: strip hyphens from the stem, then check if it is 11 bare digits
        s_no_hyphens = _normalize_ndc11(s)
        if s_no_hyphens.isdigit() and len(s_no_hyphens) == 11:
            return ndc11_map.get(s_no_hyphens)
        r = slug_map.get(s.lower())
        if r is None:
            r = name_slug_map.get(s.lower())
        return r

    # ── Phase 1: match images to pills and validate image data ────────────
    # We collect everything here before uploading so we can identify all
    # errors before any uploads start.
    pending_uploads: list[tuple] = []  # (basename, pill_id, storage_path, img_data, content_type)
    results = []
    counts = {
        "total": len(image_entries),
        "matched": 0,
        "uploaded": 0,
        "skipped": 0,
        "failed": 0,
    }

    for entry_name in image_entries:
        basename = os.path.basename(entry_name)
        stem, ext = os.path.splitext(basename)
        ext = ext.lower()

        # Match
        matched_row = _lookup(stem)
        if matched_row is None:
            base_stem = _strip_variant_suffix(stem)
            if base_stem != stem:
                matched_row = _lookup(base_stem)

        if matched_row is None:
            results.append(
                {
                    "filename": basename,
                    "pill_id": None,
                    "storage_path": None,
                    "url": None,
                    "error": "No matching pill found",
                }
            )
            counts["skipped"] += 1
            continue

        counts["matched"] += 1
        pill_id = matched_row[0]

        # Guard against zip bomb: check the declared uncompressed size before reading
        info = zf.getinfo(entry_name)
        if info.file_size > MAX_FILE_SIZE:
            results.append(
                {
                    "filename": basename,
                    "pill_id": pill_id,
                    "storage_path": None,
                    "url": None,
                    "error": "Image too large (max 5 MB)",
                }
            )
            counts["failed"] += 1
            continue

        try:
            img_data = zf.read(entry_name)
        except Exception:
            results.append(
                {
                    "filename": basename,
                    "pill_id": pill_id,
                    "storage_path": None,
                    "url": None,
                    "error": "Failed to read image from ZIP",
                }
            )
            counts["failed"] += 1
            continue

        # Final size check on actual decompressed bytes
        if len(img_data) > MAX_FILE_SIZE:
            results.append(
                {
                    "filename": basename,
                    "pill_id": pill_id,
                    "storage_path": None,
                    "url": None,
                    "error": "Image too large (max 5 MB)",
                }
            )
            counts["failed"] += 1
            continue

        unique_suffix = uuid.uuid4().hex[:8]
        timestamp_ms = int(time.time() * 1000)
        storage_filename = f"{pill_id[:8]}-{timestamp_ms}-{unique_suffix}{ext}"
        storage_path = f"{pill_id}/{storage_filename}"
        content_type = _CONTENT_TYPE_MAP.get(ext, "image/jpeg")

        pending_uploads.append((basename, pill_id, storage_path, img_data, content_type))

    # ── Phase 2: upload all matched images concurrently ───────────────────
    pill_new_paths: dict[str, list[str]] = {}

    if pending_uploads:
        sem = asyncio.Semaphore(_ZIP_UPLOAD_CONCURRENCY)

        async def _bounded_upload(basename: str, pill_id: str, storage_path: str,
                                   img_data: bytes, content_type: str) -> tuple:
            """Upload one image with concurrency throttling; returns (basename, pill_id, storage_path, ok)."""
            async with sem:
                ok = await _async_supabase_upload(storage_path, img_data, content_type)
            return (basename, pill_id, storage_path, ok)

        upload_results = await asyncio.gather(
            *[_bounded_upload(*args) for args in pending_uploads],
            return_exceptions=True,
        )

        from utils import IMAGE_BASE

        for upload_result in upload_results:
            if isinstance(upload_result, Exception):
                # This branch should not normally be reached since _bounded_upload catches errors
                logger.error(f"Unexpected upload exception: {upload_result}")
                counts["failed"] += 1
                continue

            basename, pill_id, storage_path, ok = upload_result

            if not ok and SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY:
                results.append(
                    {
                        "filename": basename,
                        "pill_id": pill_id,
                        "storage_path": None,
                        "url": None,
                        "error": "Storage upload failed",
                    }
                )
                counts["failed"] += 1
                continue

            image_url = f"{IMAGE_BASE}/{storage_path}"
            results.append(
                {
                    "filename": basename,
                    "pill_id": pill_id,
                    "storage_path": storage_path,
                    "url": image_url,
                    "error": None,
                }
            )
            counts["uploaded"] += 1
            pill_new_paths.setdefault(pill_id, []).append(storage_path)

    # ── Phase 3: write DB updates + audit log ─────────────────────────────
    # If the DB update fails after uploads have already succeeded, log the
    # orphaned storage paths so they can be manually reconciled.
    if pill_new_paths:
        orphaned_paths: list[str] = [
            path for paths in pill_new_paths.values() for path in paths
        ]
        try:
            with database.db_engine.begin() as conn:
                for pid, new_paths in pill_new_paths.items():
                    existing = conn.execute(
                        text(
                            "SELECT image_filename FROM pillfinder"
                            " WHERE id = :id LIMIT 1"
                        ),
                        {"id": pid},
                    ).fetchone()
                    if not existing:
                        continue

                    old_fn = existing[0] or ""
                    all_paths = [p.strip() for p in old_fn.split(",") if p.strip()] + new_paths
                    new_fn = ",".join(all_paths)

                    conn.execute(
                        text(
                            "UPDATE pillfinder SET image_filename = :fn,"
                            " has_image = 'TRUE', updated_at = now(),"
                            " updated_by = :uid WHERE id = :id"
                        ),
                        {"fn": new_fn, "uid": str(admin["id"]), "id": pid},
                    )

                log_audit(
                    conn,
                    actor_id=admin["id"],
                    actor_email=admin["email"],
                    action="bulk_upload_images_zip",
                    entity_type="image",
                    entity_id=None,
                    metadata={
                        "zip_filename": file.filename,
                        "total": counts["total"],
                        "matched": counts["matched"],
                        "uploaded": counts["uploaded"],
                        "skipped": counts["skipped"],
                        "failed": counts["failed"],
                    },
                    ip_address=request.client.host if request.client else None,
                    user_agent=request.headers.get("user-agent"),
                )
        except SQLAlchemyError as e:
            logger.critical(
                "upload_images_zip DB update failed after %d images were uploaded to storage."
                " These storage objects have no DB reference and must be cleaned up manually: %s",
                len(orphaned_paths),
                orphaned_paths,
            )
            logger.error(f"upload_images_zip DB update error: {e}")
            raise HTTPException(status_code=500, detail="Database error during image update")

    return {"counts": counts, "results": results}


@router.post("/{pill_id}/images")
async def upload_image(
    request: Request,
    pill_id: str,
    file: UploadFile = File(...),
    admin: dict = Depends(get_admin_user),
):
    if admin["role"] not in ("superuser", "editor", "reviewer"):
        raise HTTPException(status_code=403, detail="Requires editor role or higher")

    ext = os.path.splitext(file.filename or "")[1].lower()
    if ext not in ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=400, detail=f"Invalid file type. Allowed: {ALLOWED_EXTENSIONS}")

    content = await file.read()
    if len(content) > MAX_FILE_SIZE:
        raise HTTPException(status_code=400, detail="File too large (max 5MB)")

    timestamp = int(time.time())
    filename = f"{pill_id[:8]}-{timestamp}{ext}"
    storage_path = f"{pill_id}/{filename}"

    content_type = file.content_type or "image/jpeg"
    upload_ok = _supabase_upload(storage_path, content, content_type)
    if not upload_ok and SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY:
        # Credentials are configured but upload failed — abort to avoid a broken image reference
        raise HTTPException(status_code=502, detail="Image upload to storage failed. Please try again.")

    if not database.db_engine:
        database.connect_to_database()

    try:
        with database.db_engine.begin() as conn:
            existing = conn.execute(
                text("SELECT image_filename FROM pillfinder WHERE id = :id LIMIT 1"),
                {"id": pill_id},
            ).fetchone()
            if not existing:
                raise HTTPException(status_code=404, detail="Pill not found")

            old_filenames = existing[0] or ""
            new_filenames = (old_filenames + "," + storage_path).strip(",") if old_filenames else storage_path

            conn.execute(
                text(
                    "UPDATE pillfinder SET image_filename = :fn, has_image = 'TRUE',"
                    " updated_at = now(), updated_by = :uid WHERE id = :id"
                ),
                {"fn": new_filenames, "uid": str(admin["id"]), "id": pill_id},
            )

            from utils import IMAGE_BASE
            image_url = f"{IMAGE_BASE}/{storage_path}"

            log_audit(
                conn,
                actor_id=admin["id"],
                actor_email=admin["email"],
                action="upload_image",
                entity_type="image",
                entity_id=pill_id,
                metadata={"filename": filename, "url": image_url},
                ip_address=request.client.host if request.client else None,
                user_agent=request.headers.get("user-agent"),
            )

        return {"filename": storage_path, "url": image_url}
    except HTTPException:
        raise
    except SQLAlchemyError as e:
        logger.error(f"upload_image DB error: {e}")
        raise HTTPException(status_code=500, detail="Database error")


@router.delete("/{pill_id}/images/{filename:path}")
def delete_image(
    request: Request,
    pill_id: str,
    filename: str,
    admin: dict = Depends(get_admin_user),
):
    if admin["role"] not in ("superuser", "editor", "reviewer"):
        raise HTTPException(status_code=403, detail="Requires editor role or higher")

    # Move to deleted/ prefix in Supabase Storage.
    # `filename` may be the full storage path (new format: pill_id/bare_filename)
    # or a bare filename (legacy format). Use it directly as the source key.
    if SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY:
        try:
            httpx.post(
                f"{SUPABASE_URL}/storage/v1/object/move",
                headers={
                    "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "bucketId": STORAGE_BUCKET,
                    "sourceKey": filename,
                    "destinationKey": f"deleted/{filename}",
                },
                timeout=10,
            )
        except Exception as e:
            logger.warning(f"Could not move image to deleted/: {e}")

    if not database.db_engine:
        database.connect_to_database()

    try:
        with database.db_engine.begin() as conn:
            existing = conn.execute(
                text("SELECT image_filename FROM pillfinder WHERE id = :id LIMIT 1"),
                {"id": pill_id},
            ).fetchone()
            if not existing:
                raise HTTPException(status_code=404, detail="Pill not found")

            filenames = [f.strip() for f in (existing[0] or "").split(",") if f.strip() != filename]
            new_fn = ",".join(filenames)
            has_image = "TRUE" if filenames else "FALSE"

            conn.execute(
                text(
                    "UPDATE pillfinder SET image_filename = :fn, has_image = :hi,"
                    " updated_at = now(), updated_by = :uid WHERE id = :id"
                ),
                {"fn": new_fn, "hi": has_image, "uid": str(admin["id"]), "id": pill_id},
            )

            log_audit(
                conn,
                actor_id=admin["id"],
                actor_email=admin["email"],
                action="delete_image",
                entity_type="image",
                entity_id=pill_id,
                metadata={"filename": filename},
                ip_address=request.client.host if request.client else None,
                user_agent=request.headers.get("user-agent"),
            )

        return {"deleted": True}
    except HTTPException:
        raise
    except SQLAlchemyError as e:
        logger.error(f"delete_image DB error: {e}")
        raise HTTPException(status_code=500, detail="Database error")
